#!/bin/tcsh -f

if ($#argv != 1) then
	echo "usage: $0 <projectdir>"
	exit 1
endif


set thisDir = `dirname $0`
set mem = (-Xms200m -Xmx200m)
set cp = $thisDir/mxpost.jar

java -server $mem -cp $cp tagger.TestTagger $1
